project:
  type: website
  output-dir: docs

website:
  title: "Wendy Lucio | Risk & Analytics"
  favicon: images/favicon.png
  navbar:
    logo: images/logo.png
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Reflection"
        href: reflection.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - text: "CV"
        href: cv/WendyLucioCV.pdf
        target: _blank
      - icon: github
        href: https://github.com/WendyLucio
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/wendymlp
        target: _blank
  page-footer:
    left: "© 2026 Wendy Lucio"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true